Add workflow step to mark release as stable with final checks and notifications

diff --git a/.github/workflows/release-build-zip-file.yml b/.github/workflows/release-build-zip-file.yml
--- a/.github/workflows/release-build-zip-file.yml
+++ b/.github/workflows/release-build-zip-file.yml
@@ -1,4 +1,5 @@
 name: 'Release: Build ZIP file'
+
 on:
   workflow_dispatch:
     inputs:
@@ -10,6 +11,14 @@ on:
         description: 'Skip the PR verification step (default: false) pass true to skip'
         required: false
         default: 'false'
+      release_type:
+        description: 'Release type (e.g. stable, rc, beta)'
+        required: false
+        default: ''
+      version:
+        description: 'Release version (e.g. 9.0.0)'
+        required: false
+        default: ''
 
 permissions: {}
 
@@ -20,77 +29,68 @@ jobs:
       runBuildZipJob: ${{ steps.verify-prs.outputs.runBuildZipJob }}
     runs-on: ubuntu-latest
     steps:
-        - name: Verify if any PR is left open by author:app/github-actions
-          id: verify-prs
-          uses: actions/github-script@v6
-          with:
-              github-token: ${{ secrets.GITHUB_TOKEN }}
-              script: |
-                  let runBuildZipJob = true;
-                  const event = context.payload;
+      - name: Verify if any PR is left open by author:app/github-actions
+        id: verify-prs
+        uses: actions/github-script@v6
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            let runBuildZipJob = true;
+            const event = context.payload;
 
-                  if (event.inputs.skip_verify !== 'false') {
-                    core.setOutput('runBuildZipJob', runBuildZipJob);
-                    console.log('Skipping verification step');
-                    return;
+            if (event.inputs.skip_verify !== 'false') {
+              core.setOutput('runBuildZipJob', runBuildZipJob);
+              console.log('Skipping verification step');
+              return;
+            }
+
+            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
+            const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));
+            const searchPRs = async (query) => {
+              let attempts = 0;
+              while (attempts < 5) {
+                try {
+                  return await github.rest.search.issuesAndPullRequests({ q: query });
+                } catch (error) {
+                  if (error.status === 403 && error.message.includes('secondary rate limit')) {
+                    console.log('Rate limit hit, retrying...');
+                    await delay(31000);
+                    attempts++;
+                  } else {
+                    throw error;
                   }
+                }
+              }
+              throw new Error('Failed to fetch PRs after multiple attempts');
+            };
 
-                  const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
+            const githubActionsPRsQuery = await searchPRs(`repo:${owner}/${repo} is:pr is:open author:app/github-actions`);
+            const prsOpenByGithubActions = githubActionsPRsQuery.data.items;
+            let failureMessage = ``;
 
-                  // Helper function to add delay between API calls
-                  const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));
+            if (prsOpenByGithubActions.length > 0) {
+              runBuildZipJob = false;
+              failureMessage += `Identified \`${prsOpenByGithubActions.length}\` open PR(s) from \`github-actions\` bot which should be merged or closed before proceeding. <https://github.com/${owner}/${repo}/issues?q=is%3Apr+is%3Aopen+author%3Aapp%2Fgithub-actions|Link to PRs>`;
+              failureMessage += '\n\nThis step maintains the code integrity and is critical to avoid regression in future releases. Please merge them or close them before proceeding or set `skip_verify` to `true` before running the workflow to skip this step if you are confident that the PRs are irrelevant.';
+              console.error(failureMessage);
+              core.setOutput('failureMessage', failureMessage);
+            }
 
-                  // Function to handle API call with retry logic
-                  const searchPRs = async (query) => {
-                    let attempts = 0;
-                    while (attempts < 5) {
-                      try {
-                        return await github.rest.search.issuesAndPullRequests({ q: query });
-                      } catch (error) {
-                        if (error.status === 403 && error.message.includes('secondary rate limit')) {
-                          console.log('Rate limit hit, retrying...');
-                          await delay(31000); // 31 second delay before retry
-                          attempts++;
-                        } else {
-                          throw error;
-                        }
-                      }
-                    }
-                    throw new Error('Failed to fetch PRs after multiple attempts');
-                  };
+            core.setOutput('runBuildZipJob', runBuildZipJob);
 
-                  // Search for PRs from github-actions bot
-                  const githubActionsPRsQuery = await searchPRs(`repo:${owner}/${repo} is:pr is:open author:app/github-actions`);
-                  const prsOpenByGithubActions = githubActionsPRsQuery.data.items;
-
-                  let failureMessage = ``;
-
-                  if (prsOpenByGithubActions.length > 0) {
-                      runBuildZipJob = false;
-
-                      failureMessage += `Identified \`${prsOpenByGithubActions.length}\` open PR(s) from \`github-actions\` bot which should be merged or closed before proceeding. <https://github.com/${owner}/${repo}/issues?q=is%3Apr+is%3Aopen+author%3Aapp%2Fgithub-actions|Link to PRs>`;
-
-                      failureMessage += '\n\nThis step maintains the code integrity and is critical to avoid regression in future releases. Please merge them or close them before proceeding or set \`skip_verify\` to \`true\` before running the workflow to skip this step if you are confident that the PRs are irrelevant.';
-
-                      console.error(failureMessage);
-                      core.setOutput('failureMessage', failureMessage);
-                  }
-                  core.setOutput('runBuildZipJob', runBuildZipJob);
-
-        - name: Notify Slack on failure
-          if: ${{ steps.verify-prs.outputs.failureMessage != '' }}
-          uses: archive/github-actions-slack@v2.0.0
-          with:
-              slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
-              slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
-              slack-text: |
-                  :x: Oops we may have missed PRs left open by `github-actions` bot. WooCommerce release zip build failed.
-                  :warning-8c: ${{ steps.verify-prs.outputs.failureMessage }}
-                  <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow Run>
-              slack-optional-unfurl_links: false
-              slack-optional-unfurl_media: false
-          continue-on-error: true
-
+      - name: Notify Slack on failure
+        if: ${{ steps.verify-prs.outputs.failureMessage != '' }}
+        uses: archive/github-actions-slack@v2.0.0
+        with:
+          slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
+          slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
+          slack-text: |
+            :x: Oops we may have missed PRs left open by `github-actions` bot. WooCommerce release zip build failed.
+            :warning-8c: ${{ steps.verify-prs.outputs.failureMessage }}
+            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow Run>
+          slack-optional-unfurl_links: false
+          slack-optional-unfurl_media: false
+        continue-on-error: true
 
   build:
     name: Build release zip file
@@ -122,3 +122,58 @@ jobs:
           name: woocommerce
           path: zipfile
           retention-days: 7
+
+  mark_as_stable:
+    name: Mark release as stable
+    if: ${{ github.event.inputs.release_type == 'stable' && needs.verify.outputs.runBuildZipJob == 'true' }}
+    needs: build
+    runs-on: ubuntu-latest
+    environment:
+      name: production
+      url: https://github.com/woocommerce/woocommerce/releases
+    permissions:
+      contents: write
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up Git
+        run: |
+          git config user.name "github-actions"
+          git config user.email "actions@github.com"
+
+      - name: Verify version in plugin header
+        run: |
+          grep "Version: ${{ github.event.inputs.version }}" plugins/woocommerce/woocommerce.php || {
+            echo "❌ Version mismatch in woocommerce.php"
+            exit 1
+          }
+
+      - name: Update stable tag to this commit
+        run: |
+          git fetch origin
+          git tag -f stable ${{ github.sha }}
+          git push origin stable --force
+
+      - name: Verify no open CFE or PRR issues
+        run: |
+          open_cfes=$(gh issue list --label "CFE" --state open --json number --jq 'length')
+          open_prrs=$(gh issue list --label "PRR" --state open --json number --jq 'length')
+          if [[ "$open_cfes" -gt 0 || "$open_prrs" -gt 0 ]]; then
+            echo "❌ There are still open CFE or PRR issues."
+            exit 1
+          fi
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Notify Slack (optional)
+        env:
+          SLACK_WEBHOOK: ${{ secrets.SLACK_RELEASE_WEBHOOK }}
+        run: |
+          if [ -n "$SLACK_WEBHOOK" ]; then
+            curl -X POST -H 'Content-type: application/json' \
+              --data '{"text":"🚀 WooCommerce v${{ github.event.inputs.version }} has been marked as *stable*! 🎉"}' \
+              "$SLACK_WEBHOOK"
+          else
+            echo "No Slack webhook set. Skipping notification."
